### ISSUE TITLE
undefined method `bytesize' for Hash

### ISSUE THREAD

**Issue by eignerchris** [intridea/omniauth-oauth2#89]
I inherited a project containing a problematic omniauth-oauth2 strategy. It contains a monkey-patch for Faraday that is breaking code elsewhere in the application. Obviously I'd love to get the strategy working sans monkey patch. I've been reading other strategies and experimenting all day with no luck. If I remove the monkey patch, I always get an `undefined bytesize method` exception.

ruby 2.2.2p95
omniauth-1.3.1
omniauth-oauth2-1.4.0

The strategy in question. Checkout the commented-out monkey patch at the bottom.

````
require 'omniauth-oauth2'
require "erb"

module OmniAuth
  module Strategies
    class PGE < OmniAuth::Strategies::OAuth2
      def self.ssl_options
        {
          client_cert: OpenSSL::X509::Certificate.new(ENV.fetch("SSL_CERTIFICATE")),
          client_key: OpenSSL::PKey::RSA.new(ENV.fetch("SSL_PRIVATE_KEY")),
        }
      end

      option :client_options, {
        site: 'https://api.pge.com',
        authorize_url: authorization_url,
        token_url: token_url,
        connection_opts: { ssl: ssl_options }
      }

      def build_access_token
        verifier = request.params["code"]

        params = {
          headers: authorization_header,
          redirect_uri: callback_url,
          code: verifier,
          grant_type: "authorization_code"
        }.merge(token_params.to_hash(symbolize_keys: true))

        client.auth_code.get_token(verifier, params, deep_symbolize(options.auth_token_params))
      end

      def authorization_header
        credentials         = "#{options.client_id}:#{options.client_secret}"
        encoded_credentials = Base64.urlsafe_encode64(credentials)

        {
          "Authorization" => "Basic #{encoded_credentials}",
          "Content-Type"  => "text/plain",
        }
      end

      info do
        access_token.to_hash
      end
    end
  end
end

# module Faraday
#   class Connection
#     alias original_run_request run_request

#     # Builds and runs the Faraday::Request.
#     #
#     # method  - The Symbol HTTP method.
#     # url     - The String or URI to access.
#     # body    - The String body
#     # headers - Hash of unencoded HTTP header key/value pairs.
#     #
#     # Returns a Faraday::Response.
#     def run_request(method, url, body, headers)
#       puts method, url, body, headers
#       original_run_request(method, url, body.to_json, headers)
#     end
#   end
# end

OmniAuth.config.add_camelization 'pge', 'PGE'
````

And the exception
````
/Users/eignerchris/.rbenv/versions/2.2.2/lib/ruby/2.2.0/net/http/generic_request.rb:182:in `send_request_with_body'
/Users/eignerchris/.rbenv/versions/2.2.2/lib/ruby/2.2.0/net/http/generic_request.rb:120:in `exec'
/Users/eignerchris/.rbenv/versions/2.2.2/lib/ruby/2.2.0/net/http.rb:1412:in `block in transport_request'
/Users/eignerchris/.rbenv/versions/2.2.2/lib/ruby/2.2.0/net/http.rb:1411:in `catch'
/Users/eignerchris/.rbenv/versions/2.2.2/lib/ruby/2.2.0/net/http.rb:1411:in `transport_request'
/Users/eignerchris/.rbenv/versions/2.2.2/lib/ruby/2.2.0/net/http.rb:1384:in `request'
/Users/eignerchris/.rbenv/versions/2.2.2/lib/ruby/2.2.0/net/http.rb:1377:in `block in request'
/Users/eignerchris/.rbenv/versions/2.2.2/lib/ruby/2.2.0/net/http.rb:853:in `start'
/Users/eignerchris/.rbenv/versions/2.2.2/lib/ruby/2.2.0/net/http.rb:1375:in `request'
faraday (0.9.2) lib/faraday/adapter/net_http.rb:82:in `perform_request'
faraday (0.9.2) lib/faraday/adapter/net_http.rb:40:in `block in call'
faraday (0.9.2) lib/faraday/adapter/net_http.rb:87:in `with_net_http_connection'
faraday (0.9.2) lib/faraday/adapter/net_http.rb:32:in `call'
faraday (0.9.2) lib/faraday/request/url_encoded.rb:15:in `call'
faraday (0.9.2) lib/faraday/rack_builder.rb:139:in `build_response'
faraday (0.9.2) lib/faraday/connection.rb:377:in `run_request'
oauth2 (1.1.0) lib/oauth2/client.rb:93:in `request'
oauth2 (1.1.0) lib/oauth2/client.rb:138:in `get_token'
oauth2 (1.1.0) lib/oauth2/strategy/auth_code.rb:29:in `get_token'
lib/omniauth/strategies/pge.rb:56:in `build_access_token'
````

I get the problem -- net/http expects the body to be a string, not a Hash. I've read several closed issues regarding the bytesize error but the code in question is almost always about Faraday and the order of the middleware. In this case I don't have any control over the order of the middleware as connection is setup in the oauth2 gem. I'm at a loss. Am I missing something dumb? Any help is greatly appreciated.

**Comment by eignerchris** [comment]
So after a lot of testing, I've determined that the issue is that the endpoint we're talking to doesn't like when the request body has data in it...request params must be a query string. The default `url_encoded` middleware always sets the request body. I ended up writing a custom middleware that sets the body to an empty string. Using the middleware means that the rest of my codebase is unaffected.

````
class EmptyBody < Faraday::Middleware
  CONTENT_TYPE = 'Content-Type'.freeze unless defined? CONTENT_TYPE

  class << self
    attr_accessor :mime_type
  end
  self.mime_type = 'application/x-www-form-urlencoded'.freeze

  def call(env)
    env.body = ""
    @app.call env
  end
end
````

**Comment by growthcode** [comment]
For me, it was the endpoint not like `'Content-Type' => 'application/json',` in the header. Once removed, it worked.
